### ISSUE TITLE
failure to import main after commit b9fd95c4cce7e1c61be94951c6a8a9c521590701

### ISSUE THREAD

**Issue by jcftang** [hashdist/hashdist#259]
This recent b9fd95c4cce7e1c61be94951c6a8a9c521590701 commit introduces this problem for me

<pre>
~/hashstack$ hit build
Traceback (most recent call last):
  File "/home/jtang/hashdist/bin/hit", line 10, in <module>
    from hashdist.cli.main import command_line_entry_point, help_on_exceptions
  File "/home/jtang/hashdist/hashdist/cli/__init__.py", line 7, in <module>
    from .main import main
ImportError: cannot import name main
</pre>
