### ISSUE TITLE
hit bdir broken

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashdist#300]
`hit bdir` was broken in b570c6a4bde85092dfd2bb02ca150a0ac33c351d:

    $ hit bdir test.python.yaml python tmp
    [CRITICAL] Uncaught exception:
    [CRITICAL] Traceback (most recent call last):
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/cli/main.py", line 202, in help_on_exceptions
    [CRITICAL]     return func(*args, **kw)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/cli/main.py", line 174, in command_line_entry_point
    [CRITICAL]     retcode = args.subcommand_handler(ctx, args)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/cli/frontend_cli.py", line 49, in run
    [CRITICAL]     self = cls(ctx, args)
    [CRITICAL]   File "/home/johannr/dev/misc/hashdist/hashdist/cli/frontend_cli.py", line 43, in __init__
    [CRITICAL]     parameters = dict(args.parameters) if args.parameters else None
    [CRITICAL] AttributeError: 'Namespace' object has no attribute 'parameters'
    [CRITICAL] This exception has not been translated to a human-friendly error message,
    [CRITICAL] please file an issue at https://github.com/hashdist/hashdist/issues pasting
    [CRITICAL] this stack trace.

where `test.python.yaml` looks like this:

    extends:
    - file: debian.yaml

    packages:
      launcher:
      python:
        link: shared

**Comment by ahmadia** [comment]
Okay, that should be relatively easy to fix.

**Comment by ohanar** [comment]
See #303.

**Comment by johannesring** [comment]
Fixed in b348438d1af6128ba9897a691535542fe660f0d2.
